## Practice Questions

For each question, write your code in the cell provided and make sure it prints your final answer.

### Q1: Arrays, arange, and arithmetic

Use `np.arange` to create an array `x` containing the integers from 1 to 10. Compute and print `x + 5`, `x * 2`, and `x ** 2`. Then use `np.sqrt()` to print the square root of every element, and check its `dtype`; think about why it isn't an integer array.

In [28]:
# TODO: your code for Q1 here

In [33]:
x = np.arange(1,11)

print(x+5) # Print x+5
print(x*2) # Print x*2
print( x ** 2) # Print x squared
print(np.sqrt(x)) # Print the square root of x


[ 6  7  8  9 10 11 12 13 14 15]
[ 2  4  6  8 10 12 14 16 18 20]
[  1   4   9  16  25  36  49  64  81 100]
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]


### Q2: Evaluating a function and slicing

Create an array `x` of 9 evenly spaced values from `0` to `2 * np.pi` using `np.linspace(0, 2 * np.pi, 9)`. Compute `y = np.cos(np.sin(x))` and print both arrays. Then, using slicing, print only the first three values of `y`, only the last three, and every other value.

In [30]:
# TODO: your code for Q2 here

In [34]:
x= np.linspace(0, 2 * np.pi, 9) # 9 evenly spaced angles covering a full period
print(x) # Print the angles

y = np.cos(np.sin(x)) # Evaluate cos(sin(x)) at each of those 9 points
print(y) # Print the resulting values

print(y[:3]) # Print the first three values of y
print(y[-3:]) # Print the last three values of y
print(y[::2]) # Print every other value of y, starting with the first

[0.         0.78539816 1.57079633 2.35619449 3.14159265 3.92699082
 4.71238898 5.49778714 6.28318531]
[1.         0.7602446  0.54030231 0.7602446  1.         0.7602446
 0.54030231 0.7602446  1.        ]
[1.         0.7602446  0.54030231]
[0.54030231 0.7602446  1.        ]
[1.         0.54030231 1.         0.54030231 1.        ]


### Q3: Complex numbers, real/imaginary parts, and magnitude

Create an array `z` of 6 complex numbers of your choice (mix positive and negative real and imaginary parts). Print `z.real` and `z.imag`. Then compute the magnitude of every element two ways: (1) with a `for` loop that applies Python's built-in `abs()` to each element and prints it with an f-string, and (2) with the single vectorized call `np.abs(z)`. Confirm the two options agree with `np.allclose`, and compare how much code each option needed.

In [31]:
# TODO: your code for Q3 here

In [37]:
z = np.array([1. + 2j, 2+4j, 3+6.2j, 4+3j, 5+4j, 6+5j])
print(f"z = {z}") # Print the complex array
print(f"Real part of z: {z.real}") # Print the real part of z
print(f"Imaginary part of z: {z.imag}") # Print the imaginary part of z

abs_list =[]
for el in z:
    abs_list.append(abs(el))

print(f"Absolute value of z: {abs_list}") # Print the absolute

print(np.allclose(np.array(abs_list), np.abs(z))) # Check if the two methods give the same result")


z = [1.+2.j  2.+4.j  3.+6.2j 4.+3.j  5.+4.j  6.+5.j ]
Real part of z: [1. 2. 3. 4. 5. 6.]
Imaginary part of z: [2.  4.  6.2 3.  4.  5. ]
Absolute value of z: [np.float64(2.23606797749979), np.float64(4.47213595499958), np.float64(6.887670143089026), np.float64(5.0), np.float64(6.4031242374328485), np.float64(7.810249675906654)]
True


### Q4: Building 3D Rotation Matrices

In 3D, rotating a vector by an angle $\theta$ (in radians) around one of the coordinate axes is done by multiplying it by a $3\times 3$ **rotation matrix**. Rotation about the $x$-axis leaves the $x$-coordinate unchanged and rotates the $y$-$z$ plane; rotation about the $y$-axis leaves $y$ unchanged; rotation about the $z$-axis leaves $z$ unchanged. The three matrices are:

$$
R_x(\theta) = \begin{bmatrix} 1 & 0 & 0 \\ 0 & \cos\theta & -\sin\theta \\ 0 & \sin\theta & \cos\theta \end{bmatrix}
\qquad
R_y(\theta) = \begin{bmatrix} \cos\theta & 0 & \sin\theta \\ 0 & 1 & 0 \\ -\sin\theta & 0 & \cos\theta \end{bmatrix}
\qquad
R_z(\theta) = \begin{bmatrix} \cos\theta & -\sin\theta & 0 \\ \sin\theta & \cos\theta & 0 \\ 0 & 0 & 1 \end{bmatrix}
$$

To rotate a vector $v$ (a 1D NumPy array with 3 entries) by angle $\theta$ around a given axis, compute the matrix-vector product $R(\theta)\, v$ with `@`.

**Your task:**
1. Write three functions, `Rx(theta)`, `Ry(theta)`, and `Rz(theta)`, each taking an angle `theta` in radians and returning the corresponding $3\times 3$ rotation matrix above as a NumPy array (use `np.cos` and `np.sin`).
2. Create the vector `v = np.array([1, 0, 0])`. Using your three functions, rotate `v` by `theta = np.pi / 2` around the $x$-axis, then separately around the $y$-axis, then separately around the $z$-axis, and print all three results. Think about why each result makes sense: `v` starts pointing along the $x$-axis, so which rotation(s) should leave it unchanged?
3. a) Rotate `v` by `theta = np.pi / 4` (45 degree) around the $z$-axis, then rotate that result by another `np.pi / 4` radians (45 degrees) around the $z$-axis (i.e., apply `Rz` twice in a row). b) Compare this to rotating the original `v` once by `np.pi / 2` radians (90 degrees) around the $z$-axis, using `np.allclose(arr1, arr2)` with `arr1` and `arr2` being the NumPy array of your final results from parts a) and b), and print whether they agree.

In [32]:
# TODO: your code for Q4 here

In [ ]:
def mat_rx(theta):
    c =np.cos(theta)
    s =np.sin(theta)
    return np.array([[1, 0, 0], [0, c, -s], [0, s, c]]) # Return the 3x3 rotation matrix about the x-axis

def mat_ry(theta):
    c =np.cos(theta)
    s =np.sin(theta)
    return np.array([[c, 0, s], [0, 1, 0], [-s, 0, c]]) # Return the 3x3 rotation matrix about the y-axis

def mat_rz(theta):
    c =np.cos(theta)
    s =np.sin(theta)
    return np.array([[c, -s, 0], [s, c, 0], [0, 0, 1]]) # Return the 3x3 rotation matrix about the z-axis

v= np.array([1, 0, 0]) # A vector along the x-axis

rx = mat_rx(np.pi/2) # 90 degree rotation about the x-axis
ry = mat_ry(np.pi/2) # 90 degree rotation about the y-axis
rz = mat_rz(np.pi/2) # 90 degree rotation about the z-axis

print(f"Rotation about x-axis: {rx @ v}. This keeps the vecor intact.") # Apply the rotation matrix to the vector
print(f"Rotation about y-axis: {ry @ v}") # Apply the rotation matrix to the vector
print(f"Rotation about z-axis: {rz @ v}") # Apply the rotation matrix to the vector

rx_pi4 = mat_rz(np.pi/4) # 45 degree rotation about the z-axis
print(f"Rotation about z-axis by 45 degrees: {rx_pi4 @ v}")
twice_rotated = rx_pi4 @ (rx_pi4 @ v) # Apply the rotation matrix twice to the vector
print(f"Rotation about z-axis by another 45 degrees: {np.array2string(twice_rotated, suppress_small=True, precision=2)}") # Apply the rotation matrix twice to the vector

vz_pi2 = mat_rz(np.pi/2) @ v # 90 degree rotation about the z-axis
print(np.allclose(vz_pi2, twice_rotated)) # Check if the two methods give the same result



Rotation about x-axis: [1. 0. 0.]. This keeps the vecor intact.
Rotation about y-axis: [ 6.123234e-17  0.000000e+00 -1.000000e+00]
Rotation about z-axis: [6.123234e-17 1.000000e+00 0.000000e+00]
Rotation about z-axis by 45 degrees: [0.70710678 0.70710678 0.        ]
Rotation about z-axis by another 45 degrees: [0. 1. 0.]
True
