## Practice Questions

The five questions below cover everything in this notebook (arrays, `arange`, dtype, arithmetic, functions, random numbers, slicing, tensors, reshaping, transpose, matrix multiplication, aggregation, flipping, and unique values), ordered from easy to hard.

- New to NumPy? Focus on Q1 and Q2 (and Q3 if you have time).
- Already comfortable with arrays? Start from Q4 and work through Q5 as well.

For each question, write your code in the cell provided and make sure it prints your final answer.

### Q1: Arrays, arange, and arithmetic

Use `np.arange` to create an array `x` containing the integers from 1 to 10. Compute and print `x + 5`, `x * 2`, and `x ** 2`. Then use `np.sqrt()` to print the square root of every element, and check its `dtype`; think about why it isn't an integer array.

In [24]:
# TODO: your code for Q1 here

In [25]:
x = np.arange(1,11)

print(x+5) # Print x+5
print(x*2) # Print x*2
print( x ** 2) # Print x squared
print(np.sqrt(x)) # Print the square root of x

[ 6  7  8  9 10 11 12 13 14 15]
[ 2  4  6  8 10 12 14 16 18 20]
[  1   4   9  16  25  36  49  64  81 100]
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]


### Q2: Evaluating a function and slicing

Create an array `x` of 9 evenly spaced values from `0` to `2 * np.pi` using `np.linspace(0, 2 * np.pi, 9)`. Compute `y = np.sin(x)` and print both arrays. Then, using slicing, print only the first three values of `y`, only the last three, and every other value.

In [26]:
# TODO: your code for Q2 here

In [27]:
x= np.linspace(0, 2 * np.pi, 9) # 9 evenly spaced angles covering a full period
print(x) # Print the angles

y = np.sin(x) # Evaluate sin(x) at each of those 9 points
print(y) # Print the resulting values

print(y[:3]) # Print the first three values of y
print(y[-3:]) # Print the last three values of y
print(y[::2]) # Print every other value of y, starting with the first

[0.         0.78539816 1.57079633 2.35619449 3.14159265 3.92699082
 4.71238898 5.49778714 6.28318531]
[ 0.00000000e+00  7.07106781e-01  1.00000000e+00  7.07106781e-01
  1.22464680e-16 -7.07106781e-01 -1.00000000e+00 -7.07106781e-01
 -2.44929360e-16]
[0.         0.70710678 1.        ]
[-1.00000000e+00 -7.07106781e-01 -2.44929360e-16]
[ 0.0000000e+00  1.0000000e+00  1.2246468e-16 -1.0000000e+00
 -2.4492936e-16]


### Q3: Random sampling with a function and a loop

Using `np.random.default_rng(seed=0)`, generate an array of 200 samples from a normal distribution with mean `5` and standard deviation `2`. Write a function `count_above(arr, threshold)` that uses a `for` loop over the elements of `arr` (e.g. `for value in arr:`) to count how many exceed `threshold`. Call your function on the samples with a threshold of your choice, then check your answer against the faster, vectorized approach `np.sum(arr > threshold)`, they should match.

In [28]:
# TODO: your code for Q3 here

In [32]:
rng = np.random.default_rng(seed=0) # Create a random generator with a fixed seed

samples = rng.normal(0, 1, 200) # 200 random floats, normally distributed with mean 0 and standard deviation 1

def counter_above(arr, thereshold):
    count = 0
    for value in arr:
        if value > thereshold:
            count += 1
    return count


thereshold = 0.7
print(counter_above(samples, thereshold)) # Count how many samples are above 1
print(np.sum(samples > thereshold)) # Count how many samples are above 1 using NumPy's vectorized operations

48
48


### Q4: Reshaping and a row-by-row function

Create a 1D array with the integers from 1 to 20 using `np.arange(1, 21)`, then reshape it into a `4x5` matrix `M`. Write a function `row_summary(M)` that loops over the rows of `M` with a `for` loop (`for row in M:`) and, for each row, prints its sum and its max using an f-string. Call your function on `M`. Then verify your printed values are correct by computing `M.sum(axis=1)` and `M.max(axis=1)` directly and comparing.

In [30]:
# TODO: your code for Q4 here

In [36]:
x = np.arange(1,21)

M = x.reshape((4,5))

def row_summary(M):
    for row in M:
        print(f"Row: {row}, Sum: {np.sum(row)}, Mean: {np.max(row)}")

print(row_summary(M)) # Call the function to print the summary of each row
print(f"sum: {M.sum(axis=1)}, max: {M.max(axis=1)}") # Print the sum and max of each row using NumPy's built-in functions

Row: [1 2 3 4 5], Sum: 15, Mean: 5
Row: [ 6  7  8  9 10], Sum: 40, Mean: 10
Row: [11 12 13 14 15], Sum: 65, Mean: 15
Row: [16 17 18 19 20], Sum: 90, Mean: 20
None
sum: [15 40 65 90], max: [ 5 10 15 20]


### Q5: Matrix multiplication with a function and a loop

Write a function `apply_matrix(A, vectors)` that takes a matrix `A` and a list of 1D arrays `vectors`, and returns a new list containing `A @ v` for every `v` in `vectors`, computed using a `for` loop over the list (not a single combined matrix operation). Create a `2x2` matrix `A` of your choice and a list of three different 2D vectors, then call your function and print each transformed vector. Finally, print `A` flipped along `axis=0` and along `axis=1`.

In [31]:
A = np.array([[0, -1], [1, 0]]) # A 90-degree rotation matrix
vectors = [np.array([1, 0]), np.array([0, 1]), np.array([2, 3])]

# TODO: your code for Q5 here

In [38]:
A = np.array([[0, -1], [1, 0]]) # A 90-degree rotation matrix
vectors = [np.array([1, 0]), np.array([0, 1]), np.array([2, 3])]

def apply_matrix(A, vectors):
    list_vectors = []
    for v in vectors:
        transformed = A @ v
        print(f"Original: {v}, Transformed: {transformed}")
        list_vectors.append(transformed)
    return list_vectors

apply_matrix(A, vectors)


print(np.flip(A, axis=0)) # Flip along axis 0: reverses the ROW order (upside down)
print(np.flip(A, axis=1)) # Flip along axis 1: reverses the COLUMN order (left to right)

Original: [1 0], Transformed: [0 1]
Original: [0 1], Transformed: [-1  0]
Original: [2 3], Transformed: [-3  2]
[[ 1  0]
 [ 0 -1]]
[[-1  0]
 [ 0  1]]
