In [34]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [35]:
import numpy as np

In [36]:
x = [1,2,3,4]
np_x = np.array(x)

print(np_x, type(np_x))

[1 2 3 4] <class 'numpy.ndarray'>


In [38]:
matrix =[[1,2], [3,4]]
np_matrix = np.array(matrix)

print(matrix, type(np_matrix))

print(np_matrix.shape)

[[1, 2], [3, 4]] <class 'numpy.ndarray'>
(2, 2)


range(start, stop, step)

Numpy:
np.arange(start(int or float), stop(int or float), step (int or float))

In [40]:
for i in range(3):
    print(i)

for idx in np.arange(0.1, 1.3, 0.5):
    print(idx)

0
1
2
0.1
0.6
1.1


In [42]:
a = np.array([1, 2, 3])
print(a+2)

sines = np.sin(a)
print(sines)

[3 4 5]
[0.84147098 0.90929743 0.14112001]
