In [ ]:
# %pip install numpy

In [36]:
import numpy as np
import time

# Numpy arrays

In [42]:
list_1 = [1,2,3,4,5]
array_list_1 = np.array(list_1)

print(array_list_1, type(array_list_1))

print(array_list_1.shape)  # shape of the array

mat = [[2.1, 3.2], [4.3, 5.4]]
mat_array = np.array(mat)

print(mat_array, type(mat_array))

print(mat_array.shape)  # shape of the array

[1 2 3 4 5] <class 'numpy.ndarray'>
(5,)
[[2.1 3.2]
 [4.3 5.4]] <class 'numpy.ndarray'>
(2, 2)


np.arange(start, stop, step)

In [44]:
x = range(0, 10, 2)
print(list(x))

x_np = np.arange(-0.5, 0.5, 0.2)
print(x_np)

[0, 2, 4, 6, 8]
[-0.5 -0.3 -0.1  0.1  0.3]


np.linspace(start, stop(included), num)

In [46]:
interval_35=np.linspace(3, 5, 6, endpoint=False)

print(interval_35)

[3.         3.33333333 3.66666667 4.         4.33333333 4.66666667]


In [50]:
arr1 = np.array([1.1, 2., 3])
arr2 = np.array([4.1, 5., 6])

print(arr1 **2 )

print(np.exp(arr1))

[1.21 4.   9.  ]
[ 3.00416602  7.3890561  20.08553692]


In [ ]:
def func_sin_cos(angles, c = 0.):
    """This function computes sines and cosines

    parameters:
    angles: array of angles in radians
    c: constant to add to cosines
    """
    sines = np.sin(angles)
    cosines = np.cos(angles) + c  
    return sines, cosines

angles = np.arange(0, 2*np.pi, np.pi/2)
sins, coss = func_sin_cos(np.array([0, np.pi/2, np.pi]))

print(f"Angles: {angles}, Sines: {sins}, Cosines: {coss}")
print(f"Angles: {np.array2string(angles, precision=2, floatmode='fixed')}")


Angles: [0.         1.57079633 3.14159265 4.71238898], Sines: [0.0000000e+00 1.0000000e+00 1.2246468e-16], Cosines: [ 1.000000e+00  6.123234e-17 -1.000000e+00]
Angles: [0.00 1.57 3.14 4.71]


In [55]:
x= np.linspace(0, 2*np.pi, 20)

mat = x.reshape((4,5))
print(mat)

vec= np.array([1,2,3,4,5])

matvev= mat @ vec
print(matvev)

[[0.         0.33069396 0.66138793 0.99208189 1.32277585]
 [1.65346982 1.98416378 2.31485774 2.64555171 2.97624567]
 [3.30693964 3.6376336  3.96832756 4.29902153 4.62971549]
 [4.96040945 5.29110342 5.62179738 5.95249134 6.28318531]]
[13.22775854 38.02980581 62.83185307 87.63390034]


In [57]:
large_vec = np.linspace(0,10, 1000)


t_start = time.perf_counter()
list_sq =[]
for  el in large_vec:
    list_sq.append(el**2)
t_end = time.perf_counter()
t_elapsed = t_end - t_start
print(f"Time for list comprehension: {t_elapsed:.6f} seconds")

t_start = time.perf_counter()
array_sq = np.square(large_vec)
t_end = time.perf_counter()
t_elapsed = t_end - t_start
print(f"Time for numpy array operation: {t_elapsed:.6f} seconds")

Time for list comprehension: 0.000303 seconds
Time for numpy array operation: 0.000062 seconds
