# Introduction to Python, Part IV: NumPy

In Parts I through III we covered Python's built-in tools: variables, operators, control flow, functions, and the four core containers (lists, tuples, sets, and dictionaries). This notebook introduces **NumPy**, the standard library for numerical computing in Python. NumPy gives us the `array`, a container built specifically for fast, vectorized math on whole collections of numbers at once, which makes it the natural tool for the vectors, matrices, and functions you work with in a math class.

Each section starts with a short explanation, often including the **general form** of the syntax, followed by a code cell you can run and experiment with. Try changing the values in the code cells to see how the output changes, that's the best way to learn!

# Installing and Importing NumPy

Unlike `print()` or lists, NumPy is not part of core Python: it's a third-party package that needs to be installed once before you can use it. From a terminal, you'd run:

```
pip install numpy
```

Inside a Jupyter notebook, you can run the same kind of command directly in a code cell using `%pip install numpy`. The `%` prefix is an IPython "magic" command; it installs into the exact same environment your notebook's kernel is using. This is safer than `!pip install numpy` (running pip as a plain shell command), which can silently install into a different Python than the one running your notebook if your system has more than one. You only need to run this once per environment; if NumPy is already installed (as it usually is in a course environment), the command below will simply confirm that and exit quickly.

After installing, you import NumPy like any other module. By convention, it's almost always imported under the short alias `np`.

In [1]:
# uncomment the following line to install numpy if it is not already installed in your environment
# %pip install numpy # Run once per environment; safe to re-run, it will just confirm numpy is installed

In [1]:

import numpy as np # The standard convention: import numpy under the alias np

print(np.__version__) # Print the installed version of numpy

2.5.1


# Sequences with `np.arange`

You already know Python's built-in `range(start, stop, step)` from Parts I and II. NumPy has its own version, `np.arange`, with the same general form:

```
np.arange(start, stop, step)
```

`start` defaults to `0`, `step` defaults to `1`, and `stop` is always exclusive, exactly like `range()`. There are two key differences, though:

- `range()` produces a special, memory-light `range` object containing only integers; you need `list(...)` to see its values. `np.arange()` immediately returns an actual NumPy array, ready to use in math.
- `np.arange()` accepts non-integer steps, e.g. `np.arange(0, 1, 0.1)`, which `range()` cannot do at all.

Because of this, `np.arange` is usually the more convenient way to build a numeric array from scratch when you're already working with NumPy.

In [3]:
r = range(0, 10, 2) # A built-in range object
print(r, type(r)) # Print the value of r and its type
print(list(r)) # Convert to a list to see the actual values

a = np.arange(0, 10, 2) # The NumPy equivalent, returned directly as an array
print(a, type(a)) # Print the value of a and its type

b = np.arange(5) # start defaults to 0, step defaults to 1
print(b) # Print the array

c = np.arange(0, 1, 0.1) # A float step: not possible with range()
print(c) # Print the array of evenly spaced float values

range(0, 10, 2) <class 'range'>
[0, 2, 4, 6, 8]
[0 2 4 6 8] <class 'numpy.ndarray'>
[0 1 2 3 4]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


# Sequences with `np.linspace`

`np.linspace` is a close relative of `np.arange`, but instead of specifying the step size, you specify how many points you want. Its general form:

```
np.linspace(start, stop, num)
```

`num` (default `50`) is the number of evenly spaced points to generate between `start` and `stop`. The key difference from `np.arange` is that `linspace` includes `stop` by default, it's inclusive, whereas `arange`'s `stop` is exclusive. This makes `linspace` the natural choice whenever you're thinking "I want exactly `num` points across this interval," which comes up constantly when sampling a function to evaluate or plot it. You can exclude the endpoint with `endpoint=False` if you need `arange`-style behavior.

In [4]:
a = np.arange(0, 1, 0.25) # Step of 0.25: stop (1) is NOT included
print(a) # Print the array

b = np.linspace(0, 1, 5) # 5 evenly spaced points: stop (1) IS included
print(b) # Print the array

c = np.linspace(0, 1, 5, endpoint=False) # Same 5 points, but excluding the endpoint
print(c) # Print the array

x = np.linspace(0, 2 * np.pi, 9) # 9 evenly spaced angles covering a full period
print(x) # Print the angles

y = np.sin(x) # Evaluate sin(x) at each of those 9 points
print(y) # Print the resulting sine values

[0.   0.25 0.5  0.75]
[0.   0.25 0.5  0.75 1.  ]
[0.  0.2 0.4 0.6 0.8]
[0.         0.78539816 1.57079633 2.35619449 3.14159265 3.92699082
 4.71238898 5.49778714 6.28318531]
[ 0.00000000e+00  7.07106781e-01  1.00000000e+00  7.07106781e-01
  1.22464680e-16 -7.07106781e-01 -1.00000000e+00 -7.07106781e-01
 -2.44929360e-16]


# Creating Arrays

The core object in NumPy is the array (`np.ndarray`), an ordered grid of values, all of the same type (usually numbers). Arrays can be one-dimensional (like a vector), two-dimensional (like a matrix), or higher-dimensional.

The simplest way to create one is with `np.array`, which converts a Python list (or a list of lists, for a matrix) into an array. Its general form is:

```
np.array(object, dtype=None)
```

`object` is the list (or nested list) of values, and `dtype` optionally forces the array to use a specific data type (e.g. `int`, `float`), rather than letting NumPy guess one for you.

In [5]:
v = np.array([1, 2, 3, 4, 5]) # Create a 1D array (a vector) from a list
print(v, type(v)) # Print the value of v and its type

print(v.shape) # shape is a tuple describing the size along each dimension
print(v.dtype) # dtype is the data type of the elements: integers by default here

M = np.array([[1, 2, 3], [4, 5, 6]]) # Create a 2D array (a matrix) from a list of lists
print(M) # Print the matrix
print(M.shape) # (2, 3): 2 rows, 3 columns

[1 2 3 4 5] <class 'numpy.ndarray'>
(5,)
int64
[[1 2 3]
 [4 5 6]]
(2, 3)


By default, NumPy infers the `dtype` from your data: a list of whole numbers becomes integers, but if any value in the list is a float (or you pass `dtype=float` explicitly), the whole array becomes floats instead.

This matters more than it might seem. An integer array can only ever hold whole numbers: assigning a decimal value into it silently truncates the decimal part instead of rounding or raising an error. If you plan to store or compute decimal results later (averages, square roots, solutions to equations), it's safer to create the array with `dtype=float` from the start, even if your initial values happen to be whole numbers.

In [6]:
int_arr = np.array([1, 2, 3]) # No dtype given: NumPy infers integers from whole numbers
print(int_arr, int_arr.dtype) # Print the array and its inferred dtype

int_arr[0] = 3.9 # Try to store a decimal value in an integer array
print(int_arr) # The 3.9 was silently truncated to 3, not rounded!

float_arr = np.array([1, 2, 3], dtype=float) # Explicitly force a float dtype
print(float_arr, float_arr.dtype) # Print the array and its dtype: float64

float_arr[0] = 3.9 # Now the same assignment works correctly
print(float_arr) # 3.9 is stored exactly, as intended

[1 2 3] int64
[3 2 3]
[1. 2. 3.] float64
[3.9 2.  3. ]


Two other common ways to create arrays are `np.zeros` and `np.ones`, which build an array of a given shape filled entirely with `0`s or `1`s. Their general forms are:

```
np.zeros(shape, dtype=float)
np.ones(shape, dtype=float)
```

`shape` can be a single number (for a 1D array) or a tuple like `(rows, cols)` (for a 2D array); note that, unlike `np.array`, these default to `dtype=float` already. These are useful as starting points, for example, initializing a vector of coefficients before filling in real values.

In [7]:
z = np.zeros(5) # A 1D array of 5 zeros
print(z) # Print the array

Z = np.zeros((2, 4)) # A 2x4 matrix of zeros
print(Z) # Print the matrix

o = np.ones(5) # A 1D array of 5 ones
print(o) # Print the array

O = np.ones((3, 3)) # A 3x3 matrix of ones
print(O) # Print the matrix

[0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Sometimes you want an array filled with a specific value other than `0` or `1`, or you want to overwrite the contents of an array you already have. `np.full` creates a new array filled with a chosen value; `.fill()` overwrites every entry of an existing array in place. Their general forms:

```
np.full(shape, fill_value, dtype=None)
arr.fill(value)
```

In [8]:
sevens = np.full(5, 7) # A 1D array of five 7s
print(sevens) # Print the array

nines = np.full((3, 3), 9) # A 3x3 matrix filled with 9
print(nines) # Print the matrix

existing = np.zeros((2, 3)) # Start with a 2x3 matrix of zeros
print(existing) # Print the original matrix

existing.fill(4) # Overwrite every entry in place with 4
print(existing) # Print the updated matrix

[7 7 7 7 7]
[[9 9 9]
 [9 9 9]
 [9 9 9]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[4. 4. 4.]
 [4. 4. 4.]]


# Complex Numbers

NumPy arrays can also hold complex numbers, values with a real part and an imaginary part, written in Python with a trailing `j`, like `3 + 4j`. Passing any complex value into `np.array()` (or explicitly setting `dtype=complex`) makes the whole array complex.

Every complex array has two companion arrays you can access as attributes: `.real` gives the real part of every element, and `.imag` gives the imaginary part, each returned as a plain (real-valued) array of the same shape.

Two more tools come up constantly with complex numbers:
- `np.abs(arr)` computes the **magnitude** of every element, $\sqrt{\text{real}^2 + \text{imag}^2}$, the same formula as the length of a 2D vector `(real, imag)`.
- `np.conjugate(arr)` returns the **complex conjugate** of every element, flipping the sign of the imaginary part only (e.g. the conjugate of `3 + 4j` is `3 - 4j`).

In [9]:
c = np.array([3 + 4j, 1 - 2j, -5j, 6]) # A complex array; one complex value makes them all complex
print(c, c.dtype) # Print the array and its dtype: complex128

print(c.real) # The real part of every element, as a float array
print(c.imag) # The imaginary part of every element, as a float array

magnitudes = np.abs(c) # abs() of a complex number gives sqrt(real**2 + imag**2)
print(magnitudes) # Print the magnitudes

conjugates = np.conjugate(c) # Flip the sign of the imaginary part of every element
print(conjugates) # Print the complex conjugates


[ 3.+4.j  1.-2.j -0.-5.j  6.+0.j] complex128
[ 3.  1. -0.  6.]
[ 4. -2. -5.  0.]
[5.         2.23606798 5.         6.        ]
[ 3.-4.j  1.+2.j -0.+5.j  6.-0.j]


# Arithmetic with Arrays

One of the main reasons to use NumPy arrays instead of plain lists is that arithmetic operators work elementwise: `+`, `-`, `*`, `/`, and `**` are applied to each pair of matching entries at once, no loop required. Compare this to a regular Python list, where `+` means concatenation and `*` by a scalar means repetition, not math!

Arithmetic between an array and a single number (a scalar) applies the operation to every element (this is called broadcasting).

In [10]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

print(a + b) # Elementwise addition: [1+10, 2+20, 3+30]
print(b - a) # Elementwise subtraction
print(a * b) # Elementwise multiplication (NOT a matrix product, see below for that)
print(b / a) # Elementwise division
print(a ** 2) # Elementwise squaring

print(a * 10) # Broadcasting: multiply every element by the scalar 10
print(a + 1) # Broadcasting: add 1 to every element

list_a = [1, 2, 3]
list_b = [10, 20, 30]
print(list_a + list_b) # For plain lists, '+' means concatenation, not addition!

[11 22 33]
[ 9 18 27]
[10 40 90]
[10. 10. 10.]
[1 4 9]
[10 20 30]
[2 3 4]
[1, 2, 3, 10, 20, 30]


# NumPy Math Functions

NumPy provides vectorized versions of common math functions, `np.sin`, `np.cos`, `np.sqrt`, `np.exp`, `np.log`, and many more, which apply the function to every element of an array at once. This is especially useful for evaluating a mathematical function at many points, for example, sampling $\sin(x)$ at several angles.

In [11]:
angles = np.arange(0, np.pi / 2 + 0.01, np.pi / 6) # A few evenly spaced angles in radians
print(angles) # Print the array of angles

sines = np.sin(angles) # Evaluate sin(x) at every angle at once
print(sines) # Print the resulting sine values

cosines = np.cos(angles) # Evaluate cos(x) at every angle at once
print(cosines) # Print the resulting cosine values

values = np.array([1, 4, 9, 16, 25])
roots = np.sqrt(values) # Elementwise square root
print(roots) # Print the square roots

exps = np.exp(np.array([0, 1, 2])) # Elementwise e^x
print(exps) # Print the exponentials

logs = np.log(np.array([1, np.e, np.e ** 2])) # Elementwise natural log
print(logs) # Print the logarithms

[0.         0.52359878 1.04719755 1.57079633]
[0.        0.5       0.8660254 1.       ]
[1.00000000e+00 8.66025404e-01 5.00000000e-01 6.12323400e-17]
[1. 2. 3. 4. 5.]
[1.         2.71828183 7.3890561 ]
[0. 1. 2.]


# Writing Your Own Functions with Array Inputs

Since arrays behave like regular values, you can write your own functions that take an array as a parameter and use NumPy operations inside the function body, exactly as you defined functions with numbers or lists in Part II. This lets you package a reusable calculation, like standardizing a set of data, behind a single name.

Recall that the z-score (or standardized value) of a dataset rescales it to have mean 0 and standard deviation 1, by subtracting the mean and dividing by the standard deviation: $z = \dfrac{x - \bar{x}}{s}$.

In [12]:
def standardize(x): # x is expected to be a NumPy array
    return (x - x.mean()) / x.std() # NumPy's elementwise math does the work for every entry at once

data = np.array([2, 4, 4, 4, 5, 5, 7, 9])
z = standardize(data) # Call the function on our array
print(z) # Print the standardized values

print(z.mean()) # Should be (very close to) 0
print(z.std()) # Should be (very close to) 1

def vector_length(v): # v is expected to be a 1D NumPy array (a vector)
    return np.sqrt(np.sum(v ** 2)) # sqrt of the sum of squared components

print(vector_length(np.array([3, 4]))) # Should be 5.0: a 3-4-5 triangle

[-1.5 -0.5 -0.5 -0.5  0.   0.   1.   2. ]
0.0
1.0
5.0


# Printing Elements of Arrays

NumPy arrays are still Python objects you can loop over with a regular `for` loop, exactly like a list: `for value in arr:` visits each element in turn. This is almost always slower than a vectorized operation, but it is useful whenever you want to *do something with each element individually*, such as printing a formatted message for every entry.

An f-string (`f"..."`) is a convenient way to build that message: writing `{value}` (or `{value:.2f}` to control the number of decimal places) inside the string inserts the current value directly, without manually converting it to text with `str()` or `+`.

When all you want is to *display* the whole array with a chosen number of decimals, rather than a custom message per element, `np.array2string` does it in one call instead of a loop. Its general form:

```
np.array2string(arr, precision=2, suppress_small=True, floatmode='fixed')
```

`precision` sets how many decimals to show, `suppress_small=True` avoids switching to scientific notation for tiny values, and `floatmode='fixed'` makes every element show exactly that many decimals, matching what `{value:.2f}` gives one element at a time in the loop above.


In [13]:
temps_c = np.array([0.0, 15.0, 25.0, 37.0, 100.0]) # Some temperatures in Celsius
temps_f = temps_c * 9 / 5 + 32 # Vectorized conversion to Fahrenheit, computed all at once

for c_val, f_val in zip(temps_c, temps_f): # Loop over both arrays together, one pair at a time
    print(f"{c_val:.2f} in celsius is {f_val:.2f} in fahrenheit") # An f-string builds a formatted line for each pair, with 2 decimals each

# Compare: the loop above prints one formatted pair at a time. array2string does the whole array at once;
# floatmode='fixed' makes every element show exactly `precision` decimals, matching the :.2f used above.
print(f"{np.array2string(temps_c, precision=2, suppress_small=True, floatmode='fixed')} in celsius is "
      f"{np.array2string(temps_f, precision=2, suppress_small=True, floatmode='fixed')} in fahrenheit")


0.00 in celsius is 32.00 in fahrenheit
15.00 in celsius is 59.00 in fahrenheit
25.00 in celsius is 77.00 in fahrenheit
37.00 in celsius is 98.60 in fahrenheit
100.00 in celsius is 212.00 in fahrenheit
[  0.00  15.00  25.00  37.00 100.00] in celsius is [ 32.00  59.00  77.00  98.60 212.00] in fahrenheit


# Random Number Generators

NumPy's `random` module generates random numbers, useful for simulations, sampling, and statistics. The recommended modern approach is to create a generator with `np.random.default_rng(seed)`.

Passing a fixed `seed` makes the sequence of "random" numbers reproducible: running the cell again with the same seed gives you the same values, which is very useful when you want a repeatable experiment or homework answer.

In [14]:
rng = np.random.default_rng(seed=42) # Create a random generator with a fixed seed

uniform_sample = rng.random(5) # 5 random floats, uniformly distributed in [0, 1)
print(uniform_sample) # Print the sample

dice_rolls = rng.integers(low=1, high=7, size=10) # 10 random integers from 1 to 6 (like rolling a die)
print(dice_rolls) # Print the rolls

normal_sample = rng.normal(loc=0, scale=1, size=5) # 5 samples from a standard normal distribution
print(normal_sample) # Print the sample

normal_sample_mean_10 = rng.normal(loc=10, scale=2, size=5) # mean 10, standard deviation 2
print(normal_sample_mean_10) # Print the sample

[0.77395605 0.43887844 0.85859792 0.69736803 0.09417735]
[4 6 5 5 5 5 4 1 6 3]
[0.87939797 0.77779194 0.0660307  1.12724121 0.46750934]
[ 8.28141507 10.73750157  8.0822348  11.7569006   9.90014818]


# Indexing and Slicing

1D arrays support the same indexing and slicing syntax as lists:

```
arr[i]                # a single element
arr[start:stop:step]  # a slice
```

with negative indices and negative steps for reversing, exactly as in Part I.

In [15]:
v = np.array([10, 20, 30, 40, 50])
print(v[0]) # First element
print(v[-1]) # Last element
print(v[1:4]) # Elements at positions 1, 2, 3
print(v[::2]) # Every other element
print(v[::-1]) # The array reversed

10
50
[20 30 40]
[10 30 50]
[50 40 30 20 10]


2D arrays (matrices) add a second index for the column, with the general form:

```
M[row, col]                                # a single element
M[row_start:row_stop: row_step, col_start:col_stop:col_step]  # a sub-block
```

You can also select a whole row with `M[row, :]` (or just `M[row]`), and a whole column with `M[:, col]`.

In [16]:
M = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) # A 3x3 matrix
print(M) # Print the matrix

print(M[0, 2]) # Row 0, column 2
print(M[1, :]) # The whole second row (index 1)
print(M[:, 0]) # The whole first column (index 0)
print(M[0:2, 0:2]) # The top-left 2x2 sub-block

[[1 2 3]
 [4 5 6]
 [7 8 9]]
3
[4 5 6]
[1 4 7]
[[1 2]
 [4 5]]


Arrays with three or more dimensions are often called tensors. A 3D tensor can be thought of as a stack of matrices; indexing extends naturally with one index per dimension:

```
T[i, j, k]                                         # a single element
T[i_start:i_stop:i_step, j_start:j_stop:j_step, k_start:k_stop:k_step]  # a sub-block
```

The first index selects which matrix in the stack, and the remaining two behave just like 2D indexing within that matrix.

In [17]:
T = np.arange(24).reshape(2, 3, 4) # A 3D tensor: 2 matrices, each 3x4
print(T) # Print the whole tensor
print(T.shape) # (2, 3, 4)

print(T[0]) # The first 3x4 matrix in the stack
print(T[0, 1]) # Row 1 of the first matrix
print(T[0, 1, 2]) # A single element: matrix 0, row 1, column 2
print(T[:, :, 0]) # The first column of every matrix in the stack
print(T[1, 0:2, 1:3]) # A sub-block: matrix 1, rows 0-1, columns 1-2

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[4 5 6 7]
6
[[ 0  4  8]
 [12 16 20]]
[[13 14]
 [17 18]]


Indexing retrieves the value at a position you already know. Often you want the opposite: given a condition, find *where* it holds. `np.where(condition)` returns the indices where `condition` is `True`, its general form:

```
np.where(condition)
```

`condition` doesn't have to be an equality check, it can be any comparison, such as `x > n`. For a 1D array, `np.where` returns a tuple containing one array of matching indices; for a 2D array, it returns a tuple of two arrays, one of row indices and one of matching column indices, paired up position by position. `np.argwhere(condition)` does the same search but returns the results already paired up as an array of `[row, col]` index pairs, which is often more convenient to read or loop over. This is the NumPy analogue of a list's `.index()` method, except it finds every match at once, not just the first.

In [18]:
v = np.array([10, 20, 30, 20, 40]) # A 1D array with a repeated value

result = np.where(v == 20) # Find every index where the value is 20
print(result) # Print the raw result: a tuple containing an array of indices

indices = result[0] # Extract the array of matching indices
print(indices) # Print just the indices

first_index = indices[0] # The first matching index, like list.index() would give
print(first_index) # Print it

above_20 = np.where(v > 20) # The condition doesn't have to be equality
print(above_20[0]) # Print the indices where v is greater than 20

M = np.array([[1, 2, 3], [4, 5, 6], [3, 8, 3]]) # A 2D array with a repeated value
print(M) # Print the matrix

rows, cols = np.where(M == 3) # Row indices and column indices of every 3, paired up
print(rows) # Print the row indices
print(cols) # Print the matching column indices

for r, c in zip(rows, cols): # Loop over the matching (row, column) pairs together
    print(f"Found a 3 at row {r}, column {c}")

pairs = np.argwhere(M > 4) # Same idea, but already paired up as [row, col] entries
print(pairs) # Print the array of index pairs where M is greater than 4

(array([1, 3]),)
[1 3]
1
[2 4]
[[1 2 3]
 [4 5 6]
 [3 8 3]]
[0 2 2]
[2 0 2]
Found a 3 at row 0, column 2
Found a 3 at row 2, column 0
Found a 3 at row 2, column 2
[[1 1]
 [1 2]
 [2 1]]


There's an even more direct way to pull out the values that satisfy a condition, without needing their positions at all: **boolean masking**. Writing a condition like `x > n` on an array doesn't just give one `True`/`False`, it gives a whole new array of `True`/`False` values, one per entry, called a **boolean mask**. Indexing the original array with that mask, `x[x > n]`, keeps only the entries where the mask is `True`. General form:

```
x[condition]
```

where `condition` is any comparison built from the array itself, such as `x > n`, `x == n`, or a combination with `&` (and) / `|` (or). This works for 2D arrays too, though the result is always returned as a flat 1D array, since a filtered-out matrix generally isn't rectangular anymore.

In [19]:
x = np.array([3, -1, 4, -1, 5, -9, 2, 6])

mask = x > 0 # A boolean array: True wherever the condition holds
print(mask) # Print the mask itself

positive_values = x[mask] # Keep only the entries where mask is True
print(positive_values) # Print the filtered array

positive_values2 = x[x > 0] # The same thing, written in one line without naming the mask
print(positive_values2) # Print the filtered array

evens = x[x % 2 == 0] # Any condition works, not just comparisons to a number
print(evens) # Print only the even values

middle = x[(x > -5) & (x < 5)] # Combine conditions with & (and) / | (or); each side needs its own parentheses
print(middle) # Print values strictly between -5 and 5

x[x < 0] = 0 # You can also assign through a mask: replace every negative value with 0
print(x) # Print the updated array

M = np.array([[1, -2, 3], [-4, 5, -6]]) # A 2D array
print(M[M > 0]) # Boolean masking on a 2D array always returns a flat 1D result

[ True False  True False  True False  True  True]
[3 4 5 2 6]
[3 4 5 2 6]
[4 2 6]
[ 3 -1  4 -1  2]
[3 0 4 0 5 0 2 6]
[1 3 5]


# Array Copying

Assigning an array to a new variable, `b = a`, does **not** create a new array: `b` is just another name pointing at the same data as `a`. Slicing behaves the same way, `a[1:3]` returns a *view*, not a copy, so changing an entry through the view changes the original array too. This is different from how `+` and slicing behave on Python lists, and it's a very common source of bugs.

To get an independent array that you can modify safely, use `.copy()`:

```
b = a.copy()
```

Now `b` and `a` share no memory: changes to one never affect the other.


In [20]:
a = np.array([1, 2, 3, 4, 5])

b = a # b is NOT a new array, just another name for the same data
b[0] = 99 # Modify b...
print(a) # ...and a changes too! They are the same underlying array

view = a[1:3] # Slicing also gives a view, not a copy
view[0] = -1 # Modify the view...
print(a) # ...and a changes again, at index 1

c = a.copy() # An explicit, independent copy
c[0] = 0 # Modify c...
print(a) # ...and a is unaffected this time
print(c) # c has its own separate data

print(a is b) # True: same object
print(a is c) # False: different objects, even though .copy() started from the same values


[99  2  3  4  5]
[99 -1  3  4  5]
[99 -1  3  4  5]
[ 0 -1  3  4  5]
True
False


# Reshaping

`arr.reshape(new_shape)` rearranges the same data into a new shape, as long as the total number of elements stays the same (a 12-element array can become a `3x4` matrix, a `4x3` matrix, or a `2x2x3` tensor, but not a `5x2`). The general form is:

```
arr.reshape(new_shape)
np.reshape(arr, new_shape)
```

You can also use `-1` for one dimension to let NumPy figure it out automatically.

In [21]:
flat = np.arange(12) # A 1D array with values 0 through 11
print(flat) # Print the flat array

grid = flat.reshape(3, 4) # Reshape into a 3x4 matrix
print(grid) # Print the reshaped matrix

grid2 = flat.reshape(4, 3) # Same data, reshaped into a 4x3 matrix instead
print(grid2) # Print the reshaped matrix

grid3 = flat.reshape(2, -1) # -1 means "figure out this dimension automatically"
print(grid3) # Print the reshaped matrix: 2 rows, 6 columns inferred

back_to_flat = grid.reshape(-1) # Flatten a matrix back into a 1D array
print(back_to_flat) # Print the flattened array

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


# Transpose

The transpose of a matrix flips it over its diagonal, turning rows into columns and columns into rows. The general form:

```
arr.T
np.transpose(arr)
```

In [22]:
M = np.array([[1, 2, 3], [4, 5, 6]]) # A 2x3 matrix
print(M) # Print the original matrix
print(M.shape) # (2, 3)

M_T = M.T # Transpose using the .T attribute
print(M_T) # Print the transposed matrix
print(M_T.shape) # (3, 2): rows and columns are swapped

M_T2 = np.transpose(M) # Equivalent, using the np.transpose() function
print(M_T2) # Print the transposed matrix

[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 4]
 [2 5]
 [3 6]]
(3, 2)
[[1 4]
 [2 5]
 [3 6]]


# Matrix Multiplication

Recall that `*` between two arrays is elementwise multiplication, not the matrix product from linear algebra. For true matrix multiplication (where the number of columns of the first matrix must match the number of rows of the second), use:

```
A @ B
np.matmul(A, B)
np.dot(A, B)
```

all three are equivalent for two matrices. For example, multiplying a $2\times 2$ matrix by a column vector applies a linear transformation to that vector.

In [23]:
A = np.array([[1, 2], [3, 4]]) # A 2x2 matrix
B = np.array([[5, 6], [7, 8]]) # Another 2x2 matrix

elementwise = A * B # Elementwise product, NOT the matrix product
print(elementwise) # Print the elementwise product

matrix_product = A @ B # True matrix multiplication using the @ operator
print(matrix_product) # Print the matrix product

matrix_product2 = np.matmul(A, B) # Equivalent, using np.matmul()
print(matrix_product2) # Print the matrix product

x = np.array([1, 0]) # A column vector, written as a 1D array
transformed = A @ x # Apply the matrix A to the vector x
print(transformed) # Print the transformed vector

[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[1 3]


# Sum, Max, Min, and the `axis` Argument

`np.sum`, `np.max`, and `np.min` (also available as methods, `arr.sum()`, `arr.max()`, `arr.min()`) combine an array's values into a single summary number by default. Their general form:

```
arr.sum(axis=None)
arr.max(axis=None)
arr.min(axis=None)
```

For a 2D array, the `axis` argument lets you aggregate along just one dimension instead of over the whole array:
- `axis=0` collapses down the rows, giving one result per column.
- `axis=1` collapses across the columns, giving one result per row.

In [24]:
scores = np.array([[78, 92, 65], [88, 100, 71], [95, 60, 83]]) # 3 students (rows) x 3 quizzes (cols)
print(scores) # Print the score matrix

total = scores.sum() # Sum of every entry in the matrix
print(total) # Print the overall total

highest = scores.max() # Largest single score in the whole matrix
lowest = scores.min() # Smallest single score in the whole matrix
print(highest, lowest) # Print the max and min

quiz_totals = scores.sum(axis=0) # Sum DOWN each column: total per quiz
print(quiz_totals) # Print one total per quiz

student_totals = scores.sum(axis=1) # Sum ACROSS each row: total per student
print(student_totals) # Print one total per student

best_per_quiz = scores.max(axis=0) # Highest score achieved on each quiz
print(best_per_quiz) # Print the best score per quiz

best_per_student = scores.max(axis=1) # Each student's best quiz score
print(best_per_student) # Print the best score per student

[[ 78  92  65]
 [ 88 100  71]
 [ 95  60  83]]
732
100 60
[261 252 219]
[235 259 238]
[ 95 100  83]
[ 92 100  95]


# Reverse and Flip

You already saw that slicing with a step of `-1` (`arr[::-1]`) reverses a 1D array, just like it does for lists. For arrays with more than one dimension, `np.flip` is a clearer, explicit way to reverse the order of elements:

```
np.flip(arr, axis=None)
```

Without an `axis` argument, it reverses along every dimension at once. With `axis=0`, it flips the order of the rows (upside down); with `axis=1`, it flips the order of the columns (left to right).

In [25]:
v = np.array([1, 2, 3, 4, 5])
print(v[::-1]) # Reverse a 1D array using slicing
print(np.flip(v)) # Equivalent, using np.flip()

M = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(M) # Print the original matrix

print(np.flip(M)) # Flip along every dimension: reverses rows AND columns
print(np.flip(M, axis=0)) # Flip along axis 0: reverses the ROW order (upside down)
print(np.flip(M, axis=1)) # Flip along axis 1: reverses the COLUMN order (left to right)

[5 4 3 2 1]
[5 4 3 2 1]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]
[[7 8 9]
 [4 5 6]
 [1 2 3]]
[[3 2 1]
 [6 5 4]
 [9 8 7]]


# Unique Values

`np.unique` returns the distinct values in an array, sorted in ascending order, with duplicates removed. Its general form:

```
np.unique(arr, return_counts=False)
```

It's the NumPy analogue of converting a list to a set, but the result comes back sorted, and as an array rather than a set. Passing `return_counts=True` gives you how many times each unique value appeared and passing `return_index=True` returns the index of the first occurrence of each distinct value.

In [26]:
remainders = np.array([2.1, 0, 1.3, 2.1, 2.1, 0, 3.2, 1.3, 0]) # Remainders computed in a loop, with repeats

values, indices, counts = np.unique(remainders, return_counts=True, return_index=True) # Also get how many times each occurred
print(f"Distinct values: {values}") # Print the distinct values
print(f"Counts: {counts}") # Print how many times each value appeared, in the same order as values
print(f"Indices: {indices}") # Print the index of the first occurrence of each distinct value

Distinct values: [0.  1.3 2.1 3.2]
Counts: [3 2 3 1]
Indices: [1 2 0 6]


# Timing Your Code with `time`

When you want to compare how two pieces of code actually perform, for example the Python `for` loop from the section above versus a vectorized NumPy operation, you need a way to measure elapsed time. Python's built-in `time` module handles this; unlike NumPy, it's part of the standard library, so it just needs `import time`, no installation required.

The function to use is `time.perf_counter()`, a high-resolution clock designed specifically for timing code (prefer it over `time.time()` for benchmarking: it's monotonic and unaffected by the system clock being adjusted). Its general pattern is:

```
import time

start = time.perf_counter()   # record the clock time right before the code runs
# ... code to time ...
end = time.perf_counter()     # record the clock time right after

elapsed = end - start         # elapsed time, in seconds
```

`start` and `end` are just numbers representing a moment in time in seconds; only their *difference* is meaningful, not their individual values.

In [27]:
import time # Part of the standard library, no installation needed

n = 1_000_000
x_list = list(range(n)) # A plain Python list
x_arr = np.arange(n) # The equivalent NumPy array

start = time.perf_counter() # Start the clock
squared_loop =[]
for val in x_list:
    squared_loop.append(val ** 2) # Square every element with a Python loop
end = time.perf_counter() # Stop the clock
loop_time = end - start
print(f"Python loop:       {loop_time:.4f} seconds")

start = time.perf_counter() # Start the clock again
squared_vectorized = x_arr ** 2 # Square every element with a single vectorized NumPy operation
end = time.perf_counter() # Stop the clock
vectorized_time = end - start
print(f"NumPy vectorized:  {vectorized_time:.4f} seconds")

print(f"NumPy was about {loop_time / vectorized_time:.1f}x faster") # Compare the two timings directly

Python loop:       0.0996 seconds
NumPy vectorized:  0.0023 seconds
NumPy was about 43.8x faster


## Summary

In this notebook you learned how to:
- Install NumPy with `%pip install numpy` and import it as `np`
- Generate sequences with `np.arange(start, stop, step)`, and how it compares to Python's built-in `range()`
- Generate a fixed number of evenly spaced points with `np.linspace(start, stop, num)`, and how it compares to `np.arange`
- Create arrays with `np.array()` (from a list or list of lists), `np.zeros()`, and `np.ones()`
- Fill an array with a chosen value using `np.full()`, or overwrite an existing array's contents with `.fill()`
- Set and reason about an array's `dtype`, and why an explicit `dtype=float` matters when you need decimal precision
- Create arrays of complex numbers with `.real` and `.imag`, and find their magnitude with `np.abs()`
- Perform elementwise arithmetic (`+ - * / **`) and understand broadcasting with scalars
- Apply vectorized math functions like `np.sin()`, `np.cos()`, `np.sqrt()`, `np.exp()`, and `np.log()`
- Write your own functions that take a NumPy array as input and perform math operations on it
- Loop over an array's elements with a `for` loop and build per-element output with an f-string
- Print an array with a controlled number of decimals using `np.array2string(arr, precision=...)`
- Generate random numbers with `np.random.default_rng()`, including reproducible results using a seed
- Index and slice 1D, 2D, and 3D (tensor) arrays, including selecting rows, columns, and sub-blocks
- Find the location of values satisfying a condition with `np.where()` and `np.argwhere()`, for both 1D and 2D arrays
- Filter an array down to the values satisfying a condition with boolean masking, `x[x > n]`
- Tell the difference between a view (plain assignment or slicing) and an independent array made with `.copy()`
- Reshape arrays with `.reshape()`, including using `-1` to infer a dimension
- Transpose a matrix with `.T` or `np.transpose()`
- Perform true matrix multiplication with `@`, `np.matmul()`, or `np.dot()`, as opposed to elementwise `*`
- Aggregate arrays with `.sum()`, `.max()`, and `.min()`, using `axis` to aggregate along rows or columns
- Reverse and flip arrays with slicing and `np.flip()`
- Find distinct values with `np.unique()`, including counts
- Time code with `time.perf_counter()`, and confirm that vectorized NumPy operations are faster than an equivalent Python loop


Together with Parts I through III, you now have the core Python and NumPy tools needed to work with numerical and mathematical data.

## Practice Questions

For each question, write your code in the cell provided and make sure it prints your final answer.

### Q1: Arrays, arange, and arithmetic

Use `np.arange` to create an array `x` containing the integers from 1 to 10. Compute and print `x + 5`, `x * 2`, and `x ** 2`. Then use `np.sqrt()` to print the square root of every element, and check its `dtype`; think about why it isn't an integer array.

In [14]:
x = np.arange(1,11)
print(x+5)
print(x*2)
print(x**2)
for i in x:
    s = np.sqrt(i)
    print(f"{i:3}: sqrt = {s:5.3}, dtype={np.dtype(s)}")

[ 6  7  8  9 10 11 12 13 14 15]
[ 2  4  6  8 10 12 14 16 18 20]
[  1   4   9  16  25  36  49  64  81 100]
  1: sqrt =   1.0, dtype=float64
  2: sqrt =  1.41, dtype=float64
  3: sqrt =  1.73, dtype=float64
  4: sqrt =   2.0, dtype=float64
  5: sqrt =  2.24, dtype=float64
  6: sqrt =  2.45, dtype=float64
  7: sqrt =  2.65, dtype=float64
  8: sqrt =  2.83, dtype=float64
  9: sqrt =   3.0, dtype=float64
 10: sqrt =  3.16, dtype=float64


### Q2: Evaluating a function and slicing

Create an array `x` of 9 evenly spaced values from `0` to `2 * np.pi` using `np.linspace(0, 2 * np.pi, 9)`. Compute `y = np.cos(np.sin(x))` and print both arrays. Then, using slicing, print only the first three values of `y`, only the last three, and every other value.

In [15]:
x = np.linspace(0,2*np.pi,9)
y = np.cos(np.sin(x))
print(x)
print(y)
print(y[:3])
print(y[-3:])
print(y[::2])

[0.         0.78539816 1.57079633 2.35619449 3.14159265 3.92699082
 4.71238898 5.49778714 6.28318531]
[1.         0.7602446  0.54030231 0.7602446  1.         0.7602446
 0.54030231 0.7602446  1.        ]
[1.         0.7602446  0.54030231]
[0.54030231 0.7602446  1.        ]
[1.         0.54030231 1.         0.54030231 1.        ]


### Q3: Complex numbers, real/imaginary parts, and magnitude

Create an array `z` of 6 complex numbers of your choice (mix positive and negative real and imaginary parts). Print `z.real` and `z.imag`. Then compute the magnitude of every element two ways: (1) with a `for` loop that applies Python's built-in `abs()` to each element and prints it with an f-string, and (2) with the single vectorized call `np.abs(z)`. Confirm the two options agree with `np.allclose`, and compare how much code each option needed.

In [32]:
z = np.array([1+1j,1-1j,-1+1j,-1-1j,2,3])
print(z.real)
print(z.imag)

for i in z:
    print(f"{i:8}: magnitude = {abs(i):.8}")

print(np.abs(z))

[ 1.  1. -1. -1.  2.  3.]
[ 1. -1.  1. -1.  0.  0.]
  (1+1j): magnitude = 1.4142136
  (1-1j): magnitude = 1.4142136
 (-1+1j): magnitude = 1.4142136
 (-1-1j): magnitude = 1.4142136
  (2+0j): magnitude = 2.0
  (3+0j): magnitude = 3.0
[1.41421356 1.41421356 1.41421356 1.41421356 2.         3.        ]


### Q4: Building 3D Rotation Matrices

In 3D, rotating a vector by an angle $\theta$ (in radians) around one of the coordinate axes is done by multiplying it by a $3\times 3$ **rotation matrix**. Rotation about the $x$-axis leaves the $x$-coordinate unchanged and rotates the $y$-$z$ plane; rotation about the $y$-axis leaves $y$ unchanged; rotation about the $z$-axis leaves $z$ unchanged. The three matrices are:

$$
R_x(\theta) = \begin{bmatrix} 1 & 0 & 0 \\ 0 & \cos\theta & -\sin\theta \\ 0 & \sin\theta & \cos\theta \end{bmatrix}
\qquad
R_y(\theta) = \begin{bmatrix} \cos\theta & 0 & \sin\theta \\ 0 & 1 & 0 \\ -\sin\theta & 0 & \cos\theta \end{bmatrix}
\qquad
R_z(\theta) = \begin{bmatrix} \cos\theta & -\sin\theta & 0 \\ \sin\theta & \cos\theta & 0 \\ 0 & 0 & 1 \end{bmatrix}
$$

To rotate a vector $v$ (a 1D NumPy array with 3 entries) by angle $\theta$ around a given axis, compute the matrix-vector product $R(\theta)\, v$ with `@`.

**Your task:**
1. Write three functions, `Rx(theta)`, `Ry(theta)`, and `Rz(theta)`, each taking an angle `theta` in radians and returning the corresponding $3\times 3$ rotation matrix above as a NumPy array (use `np.cos` and `np.sin`).
2. Create the vector `v = np.array([1, 0, 0])`. Using your three functions, rotate `v` by `theta = np.pi / 2` around the $x$-axis, then separately around the $y$-axis, then separately around the $z$-axis, and print all three results. Think about why each result makes sense: `v` starts pointing along the $x$-axis, so which rotation(s) should leave it unchanged?
3. a) Rotate `v` by `theta = np.pi / 4` (45 degree) around the $z$-axis, then rotate that result by another `np.pi / 4` radians (45 degrees) around the $z$-axis (i.e., apply `Rz` twice in a row). b) Compare this to rotating the original `v` once by `np.pi / 2` radians (90 degrees) around the $z$-axis, using `np.allclose(arr1, arr2)` with `arr1` and `arr2` being the NumPy array of your final results from parts a) and b), and print whether they agree.

In [46]:
def Rx(theta):
    return np.array(
        [
            [1,0,0],
            [0,np.cos(theta),-np.sin(theta)],
            [0,np.sin(theta),np.cos(theta)]
        ]
    )

def Ry(theta):
    return np.array(
        [
            [np.cos(theta),0,np.sin(theta)],
            [0,1,0],
            [-np.sin(theta),0,np.cos(theta)]
        ]
    )

def Rz(theta):
    return np.array(
        [
            [np.cos(theta), -np.sin(theta), 0],
            [np.sin(theta), np.cos(theta), 0],
            [0,0,1]
        ]
    )

v = np.array([1,0,0])

theta_90 = np.pi / 2

x_rotate_90 = Rx(theta_90) @ v
y_rotate_90 = Ry(theta_90) @ v
z_rotate_90 = Rz(theta_90) @ v

print(x_rotate_90)
print(y_rotate_90)
print(z_rotate_90)

theta_45 = np.pi / 4

z_rotate_45_45 = Rz(theta_45) @ (Rz(theta_45) @ v) 

print(z_rotate_45_45)

print(np.allclose(z_rotate_90, z_rotate_45_45))



[1. 0. 0.]
[ 6.123234e-17  0.000000e+00 -1.000000e+00]
[6.123234e-17 1.000000e+00 0.000000e+00]
[2.22044605e-16 1.00000000e+00 0.00000000e+00]
True
